### ISSUE TITLE
API失效

### ISSUE THREAD

**Issue by andyz168** [xAsiimov/Netease-Get#1]
接口已经失效不能获取歌曲列表

**Comment by xAsiimov** [comment]
今晚进行修改, 换成另一个API

**Comment by xAsiimov** [comment]
已经更新, 请下载最新的Release.

**Comment by andyz168** [comment]
我试了下，歌单有200多首，为啥接口返回的结果是10条

**Comment by xAsiimov** [comment]
> 我试了下，歌单有200多首，为啥接口返回的结果是10条

这个API好像只给返回十条......我再找找有没有别的可用的API

**Comment by andyz168** [comment]
> > 我试了下，歌单有200多首，为啥接口返回的结果是10条
> 
> 这个API好像只给返回十条......我再找找有没有别的可用的API

https://www.bzqll.com/2018/10/39.html
https://api.hibai.cn/api/demo/index

这里有，返回的json 看下要改结构不

**Comment by xAsiimov** [comment]
> > > 我试了下，歌单有200多首，为啥接口返回的结果是10条
> > 
> > 
> > 这个API好像只给返回十条......我再找找有没有别的可用的API
> 
> https://www.bzqll.com/2018/10/39.html
> https://api.hibai.cn/api/demo/index
> 
> 这里有，返回的json 看下要改结构不

修改好了, 可以获取完整歌单了, 谢谢.
[Test.zip](https://github.com/xAsiimov/Netease-Get/files/2887376/Test.zip)

**Comment by andyz168** [comment]
> > > > 我试了下，歌单有200多首，为啥接口返回的结果是10条
> > > 
> > > 
> > > 这个API好像只给返回十条......我再找找有没有别的可用的API
> > 
> > 
> > https://www.bzqll.com/2018/10/39.html
> > https://api.hibai.cn/api/demo/index
> > 这里有，返回的json 看下要改结构不
> 
> 修改好了, 可以获取完整歌单了, 谢谢.
> [Test.zip](https://github.com/xAsiimov/Netease-Get/files/2887376/Test.zip)

厉害，下面研究下看能不能批量下载flac，我有时间也找找

**Comment by xAsiimov** [comment]
https://github.com/YongHaoWu/NeteaseCloudMusicFlac
我去看看这个项目是怎么实现的
